sudo: required
services:
  - docker

before_install:
  - docker build -t mariustudor/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true mariustudor/react-test npm test

after_success:
  - docker build -t mariustudor/multi-client ./client
  - docker build -t mariustudor/multi-nginx ./nginx
  - docker build -t mariustudor/multi-server ./server
  - docker build -t mariustudor/multi-worker ./worker

#login to dicker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push the images to docker hub
  - docker push mariustudor/multi-client
  - docker push mariustudor/multi-nginx
  - docker push mariustudor/multi-server
  - docker push mariustudor/multi-worker
