sudo: required
services:
  - docker

before_install:
  - docker build -t mariustudor/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true mariustudor/react-test npm test

after_success:
  - docker build -t mariustudor/multi-client ./client
  - docker build -t mariustudor/multi-nginx ./nginx
  - docker build -t mariustudor/multi-server ./server
  - docker build -t mariustudor/multi-worker ./worker

#login to dicker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push the images to docker hub
  - docker push mariustudor/multi-client
  - docker push mariustudor/multi-nginx
  - docker push mariustudor/multi-server
  - docker push mariustudor/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app:  multi-docker-2
  env: MultiDocker2-env
  bucket_name: elasticbeanstalk-us-east-1-717850657280
  buchet_path: docket-multi-2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  

